# Generated by Django 6.0.2 on 2026-02-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_law_battingstat_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='description',
            new_name='content',
        ),
    ]
