# Generated by Django 6.0.2 on 2026-02-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_rename_description_law_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='content',
        ),
        migrations.AlterField(
            model_name='law',
            name='number',
            field=models.IntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='LawSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('law', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='stats.law')),
            ],
        ),
    ]
