# Generated by Django 6.0.2 on 2026-02-26 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_remove_law_content_alter_law_number_lawsubsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='BowlingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('innings', models.IntegerField(default=0)),
                ('overs', models.FloatField(default=0.0)),
                ('wickets', models.IntegerField(default=0)),
                ('average', models.FloatField(blank=True, null=True)),
                ('economy', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bowling_stats', to='stats.player')),
            ],
        ),
    ]
