# Generated by Django 6.0.2 on 2026-02-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_bowlingstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlingstat',
            name='best_bowling_figures',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
