# Generated by Django 6.0.2 on 2026-02-27 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_bowlingstat_best_bowling_figures'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('innings', models.IntegerField(default=0)),
                ('catch', models.IntegerField(default=0.0)),
                ('stump_out', models.IntegerField(default=0)),
                ('dismisals', models.IntegerField(default=0)),
                ('dismisals_per_inning', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fielding_stats', to='stats.player')),
            ],
        ),
    ]
