# Generated by Django 6.0.2 on 2026-02-27 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0007_fieldingstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='all_rounder_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='AllRounderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=10)),
                ('batting_average', models.FloatField(blank=True, null=True)),
                ('bowling_average', models.FloatField(blank=True, null=True)),
                ('all_rounder_rating', models.FloatField(default=0.0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_rounder_stats', to='stats.player')),
            ],
        ),
    ]
