# Generated by Django 6.0.2 on 2026-02-27 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0008_player_all_rounder_score_alter_player_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllRounderStat',
        ),
    ]
