# Generated by Django 6.0.2 on 2026-02-27 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0009_delete_allrounderstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllRounderStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=20)),
                ('all_rounder_rating', models.FloatField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.player')),
            ],
        ),
    ]
