# Generated by Django 6.0.2 on 2026-02-27 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0010_allrounderstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='all_rounder_score',
        ),
    ]
