# Generated by Django 6.0.2 on 2026-03-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0011_remove_player_all_rounder_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.ImageField(default='player_pics/default.png', upload_to='player_pics/'),
        ),
    ]
