# Generated by Django 6.0.3 on 2026-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0012_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='ai_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
