# Generated by Django 6.0.3 on 2026-03-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0013_player_ai_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstat',
            name='innings',
            field=models.IntegerField(default=0),
        ),
    ]
