# Generated by Django 6.0.3 on 2026-03-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0014_battingstat_innings'),
    ]

    operations = [
        migrations.AddField(
            model_name='allrounderstat',
            name='innings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allrounderstat',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allrounderstat',
            name='wickets',
            field=models.IntegerField(default=0),
        ),
    ]
