# Generated by Django 6.0.3 on 2026-03-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0015_allrounderstat_innings_allrounderstat_runs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allrounderstat',
            old_name='innings',
            new_name='innings_bat',
        ),
        migrations.RenameField(
            model_name='allrounderstat',
            old_name='runs',
            new_name='runs_bat',
        ),
        migrations.AddField(
            model_name='allrounderstat',
            name='innings_bowl',
            field=models.IntegerField(default=0),
        ),
    ]
