# Generated by Django 6.0.3 on 2026-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0016_rename_innings_allrounderstat_innings_bat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstat',
            name='centuries',
            field=models.IntegerField(db_column='100', default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='ducks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='half_centuries',
            field=models.IntegerField(db_column='50', default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='highest_score',
            field=models.IntegerField(default=0),
        ),
    ]
