# Generated by Django 6.0.3 on 2026-03-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0017_battingstat_centuries_battingstat_ducks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battingstat',
            name='highest_score',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
