# Generated by Django 6.0.3 on 2026-03-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0018_alter_battingstat_highest_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='battingstat',
            name='fours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='not_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='sixes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='battingstat',
            name='span',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
