# Generated by Django 6.0.3 on 2026-03-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0019_battingstat_fours_battingstat_not_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bowlingstat',
            name='balls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='five_wic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='four_wic',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='span',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bowlingstat',
            name='strike_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fieldingstat',
            name='matches',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fieldingstat',
            name='span',
            field=models.CharField(blank=True, default='0', max_length=10, null=True),
        ),
    ]
